### PR TITLE
Minified files in archive

### PR DESCRIPTION
**Pull request by vitkarpov**
It turns out there are no minified files inside distributives.

### CODE REVIEW

**Comment by NikolayRys** [comment]
Great observation. But there is a little bit more to it.
Though the zip task now services a bit different purpose. In agreement with the Ilya Birman, the packaged version needs to be just two files: likely.css and likely.js.

So we need to amend the script itself to take only the two minified files and rename them from (likely.min.css -> likely.css).

**Comment by vitkarpov** [comment]
Makes sense, will do!

**Comment by vitkarpov** [comment]
I'd suggest change the build in a way that likely.* would be *minified*. Instead of having *.min files, we'd have *.dev files unmodified. @NikolayRys what do you think?

**Comment by NikolayRys** [comment]
I have considered it but feels a bit unusual - people won't be expecting it and immediately be able to tell, what's going on, without manually open the build files. 
Because ".dev" kinda implies more than "min" does. It's not unreasonable to assume that 
"dev", for example, may have more console logging or some other instrumentation.

**Comment by vitkarpov** [comment]
> I have considered it but this feels a bit unusual - people won't be expecting it, and immediately be able to tell what's going on, without manually open the build files.
> Because ".dev" kinda implies more than "min" does. It's not unreasonable to assume that
> "dev", for example, may have more console logging or some other instrumentation.
> 
> but maybe I have a skewed perspective as a back-end developer :)

Not at all, actually I have the same feeling. From the other perspective changing the meaning here feels like backward compatibility, without explicit renaming them before zipping in. Anyway, just wanted to talk about it 😄

**Comment by NikolayRys** [comment]
Not sure this will work 🤔 
`mv release/likely.min.js release/likely.js` will probably fail, because this file already exists. Have you tried it in your console?

**Comment by vitkarpov** [comment]
Yep, I check it works. Probably you're confusing with moving folders when it says "directory not empty".

**Comment by NikolayRys** [comment]
Sorry, but I'm not yet sure it's the way to do it. Consider this:
It deletes and rewrites the files in the current release. We'll need to run git reset each time after such packing. I suggest to do something like this:
```
mkdir release/zip
cp release/likely.min.css release/zip/likely.css
cp release/likely.min.js release/zip/likely.js
cross-env-shell bestzip release/$npm_package_name-$npm_package_version.zip release/zip/likely.css release/zip/likely.js
rm -rf release/zip
```

**Comment by vitkarpov** [comment]
@NikolayRys Excuse me for the delay, fixed! Pls, check it out once again, thanks.

**Pull request merged**
