### PR TITLE
Keep unminified JS files in builds

### LINKED ISSUE #149: Use likely.min.js for the file name in release
Please, use _min_ postfix for minified version of the lib. Having both minified and non-minified versions of the same file in release would also be cool. Thanks.

### PR DESCRIPTION
**Pull request by vitkarpov**
Fixes #149

**This is a breaking change!** (for `3.x` release)

👆 that's how build folder looks like after running `npm run-script build`. What's been `likely` before turns into `likely.min` now and `likely` file is unminified instead.

### How does it work

Minification feature is built-in and runs under `-p` flag. There are 2 configs now: base is what we already have and `webpack.config.min.js` *inherits the base one*. The min config has "min-postfixed keys" in entries to get `[name].min.js` files.

`npm run-script build` runs Webpack twice: one without `-p` mode with the base config and another *in production mode* (that's where minifications come) with the min config (to get proper file names).

### CODE REVIEW

**Comment by vitkarpov** [comment]
@NikolayRys I'm not sure why tests fail 🤔 Is it something CI specific? I didn't notice that locally, will take a closer look then.

**Comment by NikolayRys** [comment]
Hi, thank you for the pull request, we need it for 3.0.

I'm a bit busy right now, but I'll review this one and other PRs next week.

**Comment by NikolayRys** [comment]
@vitkarpov, awesome job, thank you! 
* Please merge/rebase from master: it'll fix the Travis build.
* Also, please change commit messages to follow GitHub commit style: https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53
Essentially you just need to remove feat/chore in the beginning and capitalize the rest.

**Comment by vitkarpov** [comment]
@NikolayRys done 👌

**Comment by vitkarpov** [comment]
@NikolayRys I reviewed this PR one again and noticed a thing I'm not sure about and one thing that probably needs to be fixed:

- there are 2 files: `likely.js` & `likely-common.js` but actually they are the same since it's Webpack universal module definition, so a single file works both in the browser and node.js, what do you think? (please, look at built files)
- `likely.css` becomes unminified. Do we need `likely.min.css` or leave `likely.css` minified?

**Comment by vitkarpov** [comment]
> there are 2 files: likely.js & likely-common.js but actually they are the same since it's Webpack universal module definition, so a single file works both in the browser and node.js, what do you think? (please, look at built files)

Nah, I see the difference now:

```js
window.addEventListener('load', () => {
    likely.initiate();
});
```

Everything's fine then.

**Comment by NikolayRys** [comment]
Oh, it's a very good point about css. I think, we need to be consistent now and have likely.min.js minified as well, could you please add it too?

Also, please remove the 3.0.0 bump, we are not there yet to finalize release, and there will be several more changes to it, here's the list: #163 
It's okay if this change brakes it because it happens only in the master, which is not meant to be stable.

**Comment by vitkarpov** [comment]
>  I think, we need to be consistent now and have likely.min.css minified as well, could you please add it too?

Yes, will do within this PR.

> Also, please remove the 3.0.0 bump, we are not there yet to finalize the release

Gotcha, do we need to add built files to the repo then? Anyway, it shouldn't hurt anybody.

**Comment by vitkarpov** [comment]
@NikolayRys Done 🎉

**Comment by NikolayRys** [comment]
Thanks for the good work, this was a useful change. 

About the builds, we were keeping them always in this project in the repo, it's just for consistency and for the case if somebody wants the edge version :)

**Pull request merged**
