### PR TITLE
CSS improvements according to issue#204

### PR DESCRIPTION
**Pull request by Ronef**

### CODE REVIEW

**Comment by NikolayRys** [comment]
Hi, thanks for your contribution. 

However, there is a minor issue, I have been working on a bug with CSS in the 3.0 version, can you please update your code?

**Comment by Ronef** [comment]
@NikolayRys
OK, I've just resolved the conflict right here)

**Comment by NikolayRys** [comment]
Thanks, let me test it 👍

**Comment by NikolayRys** [comment]
Yes, looking good. I'm merging it.
I will release it as 3.1, along with the rest of the fixes I have worked on.

**Pull request merged**
